#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -o errexit
# Return value of a pipeline is the status of the last command to exit with a non-zero status
set -o pipefail
# Treat unset variables as an error when substituting
set -o nounset


python manage.py migrate

# Start the server
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
