# Generated by Django 5.1.6 on 2025-05-27 21:06

import django.db.models.deletion
import quantityfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('barcode', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('energy', quantityfield.fields.QuantityField(base_units='kJ', null=True, unit_choices=['kJ', 'kcal'])),
            ],
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_unit_in_form', models.CharField(choices=[('mg', 'mg'), ('µg', 'µg')], default='mg', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FoodVitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', quantityfield.fields.QuantityField(base_units='mg', unit_choices=['mg', 'µg'])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.vitamin')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(through='foods.FoodVitamin', to='foods.vitamin'),
        ),
    ]
