# Generated by Django 5.2.3 on 2025-07-01 19:05

import django.db.models.deletion
import quantityfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('barcode', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('energy', quantityfield.fields.QuantityField(base_units='kJ', null=True, unit_choices=['kJ', 'kcal'])),
            ],
        ),
        migrations.CreateModel(
            name='Macronutrient',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('emojis', models.CharField(blank=True, max_length=100, null=True)),
                ('default_unit_in_form', models.CharField(choices=[('mg', 'mg'), ('µg', 'µg')], default='mg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMacronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', quantityfield.fields.QuantityField(base_units='g', null=True, unit_choices=['g'])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('macronutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.macronutrient')),
            ],
            options={
                'verbose_name': 'Food Macronutrient',
                'verbose_name_plural': 'Food Macronutrients',
                'ordering': ['food', 'macronutrient'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='macronutrients',
            field=models.ManyToManyField(related_name='foods', through='foods.FoodMacronutrient', to='foods.macronutrient'),
        ),
        migrations.CreateModel(
            name='FoodVitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', quantityfield.fields.QuantityField(base_units='mg', null=True, unit_choices=['mg', 'µg'])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.vitamin')),
            ],
            options={
                'verbose_name': 'Food Vitamin',
                'verbose_name_plural': 'Food Vitamins',
                'ordering': ['food', 'vitamin'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(related_name='foods', through='foods.FoodVitamin', to='foods.vitamin'),
        ),
    ]
