# Generated by Django 5.2.3 on 2025-08-07 22:31

import foods.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='barcode',
            field=foods.fields.EAN13Field(max_length=13, primary_key=True, serialize=False, validators=[foods.fields.validate_ean13, foods.fields.validate_ean13]),
        ),
    ]
