# Generated by Django 5.1.6 on 2025-05-28 16:33

import django.db.models.deletion
import quantityfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_macronutrient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodvitamin',
            options={'ordering': ['food', 'vitamin'], 'verbose_name': 'Food Vitamin', 'verbose_name_plural': 'Food Vitamins'},
        ),
        migrations.CreateModel(
            name='FoodMacronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', quantityfield.fields.QuantityField(base_units='g', null=True, unit_choices=['g'])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('macronutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.macronutrient')),
            ],
            options={
                'verbose_name': 'Food Macronutrient',
                'verbose_name_plural': 'Food Macronutrients',
                'ordering': ['food', 'macronutrient'],
            },
        ),
    ]
