# Generated by Django 5.2.3 on 2025-08-24 21:34

import foods.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='barcode',
            field=foods.fields.EAN13Field(max_length=13, primary_key=True, serialize=False),
        ),
    ]
