# Generated by Django 5.1.6 on 2025-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_foodvitamin_options_foodmacronutrient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamin',
            name='emojis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
