# Generated by Django 5.2.3 on 2025-09-20 15:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitamin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vitamin',
            name='emojis',
        ),
        migrations.AddField(
            model_name='vitamin',
            name='atc_code',
            field=models.CharField(default=0, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamin',
            name='chembl_id',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamin',
            name='common_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='macronutrient',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='vitamin',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_vitamin_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='vitamin',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('atc_code'), name='unique_vitamin_atc_code_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='vitamin',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('chembl_id'), name='unique_vitamin_chembl_id_case_insensitive'),
        ),
    ]
