# Generated by Django 5.1.6 on 2025-05-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_vitamin_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
