# Generated by Django 5.2.3 on 2025-09-20 15:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_vitamin_description_remove_vitamin_emojis_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='macronutrient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_macronutrient_name_case_insensitive'),
        ),
    ]
