# Generated by Django 5.2.1 on 2025-06-03 21:48

import quantityfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodvitamin',
            name='amount',
            field=quantityfield.fields.QuantityField(base_units='mg', null=True, unit_choices=['mg', 'µg']),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='default_unit_in_form',
            field=models.CharField(choices=[('mg', 'mg'), ('µg', 'µg')], default='mg', max_length=10),
        ),
    ]
