# Generated by Django 5.2.3 on 2026-10-03 17:18

import django.core.validators
import django.db.models.deletion
import opennutrilab.products.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', opennutrilab.products.fields.EAN13Field(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_level_1', models.CharField(blank=True, max_length=100)),
                ('group_level_2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('attribution', models.TextField(blank=True, help_text='What the licence requires to be shown wherever its data is used.')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kJ', 'kJ'), ('g', 'g'), ('mg', 'mg'), ('µg', 'µg')], max_length=3)),
                ('group', models.CharField(choices=[('energy', 'Energy'), ('macronutrient', 'Macronutrient'), ('mineral', 'Mineral'), ('vitamin', 'Vitamin'), ('other', 'Other')], max_length=20)),
                ('on_label', models.BooleanField(default=False, help_text='Part of the nutrition declaration the product form asks for.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('ciqual_code', models.CharField(blank=True, help_text='Code of the matching constituent in the CIQUAL table.', max_length=10, null=True, unique=True)),
                ('off_key', models.CharField(blank=True, help_text='OpenFoodFacts nutriment key, e.g. saturated-fat.', max_length=50, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='The nutrient this one is part of: sugars are carbohydrates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.nutrient')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SourceFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="The food's identifier in its source.", max_length=50)),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('food_group', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='products.source')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_foods', models.ManyToManyField(blank=True, related_name='reference_ingredients', to='products.sourcefood')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFoodNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, help_text='Empty when the source did not measure it. Below the detection limit, this is the limit.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='Amount cannot be negative')])),
                ('qualifier', models.CharField(choices=[('exact', 'Exact'), ('less_than', 'Below the detection limit'), ('traces', 'Traces')], default='exact', max_length=10)),
                ('confidence', models.CharField(blank=True, help_text="The source's own grade, e.g. CIQUAL's A (best) to D.", max_length=5)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='products.sourcefood')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.nutrient')),
                ('derived', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.nutrient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('derived', 'component'), name='unique_nutrient_component')],
            },
        ),
        migrations.CreateModel(
            name='ProductNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Amount cannot be negative')])),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.nutrient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_nutrients', to='products.product')),
            ],
            options={
                'ordering': ['nutrient__display_order', 'nutrient__code'],
                'constraints': [models.UniqueConstraint(fields=('product', 'nutrient'), name='unique_declared_nutrient')],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Share of the product, as declared on the label.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Percentage cannot be negative'), django.core.validators.MaxValueValidator(100, message='Percentage too large')])),
                ('off_id', models.CharField(blank=True, default='', help_text='OpenFoodFacts taxonomy id, e.g. en:oat-flakes.', max_length=255)),
                ('off_ciqual_food_code', models.CharField(blank=True, default='', max_length=10)),
                ('off_ciqual_proxy_food_code', models.CharField(blank=True, default='', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ingredients', to='products.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='products.referenceingredient')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'parent', 'name'), name='unique_ingredient_per_product_parent'), models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('product', 'name'), name='unique_root_ingredient_per_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcefood',
            constraint=models.UniqueConstraint(fields=('source', 'code'), name='unique_food_per_source'),
        ),
        migrations.AddConstraint(
            model_name='sourcefoodnutrient',
            constraint=models.UniqueConstraint(fields=('food', 'nutrient'), name='unique_nutrient_per_source_food'),
        ),
    ]
