# Generated by Django 5.2.3 on 2026-10-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_label_nutrients'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientTaxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_id', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('name_fr', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['off_id'],
            },
        ),
    ]
