# Generated by Django 5.2.3 on 2025-11-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_macronutrients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macronutrient',
            options={'verbose_name': 'Macronutrient', 'verbose_name_plural': 'Macronutrients'},
        ),
        migrations.AddField(
            model_name='macronutrient',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If defined, this macronutrient is a subcategory of another one.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subnutrients', to='products.macronutrient'),
        ),
    ]
