# Generated by Django 5.2.3 on 2025-11-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_link_submacronutrients_to_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macronutrient',
            options={},
        ),
        migrations.RemoveField(
            model_name='macronutrient',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='macronutrient',
            name='parent',
        ),
        migrations.AddField(
            model_name='macronutrient',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
