# Generated by Django 5.2.3 on 2026-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ingredient_is_its_reference'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referenceingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'curated'), _negated=True), models.Q(('name_en', ''), _negated=True), _connector='OR'), name='curated_reference_has_name_en', violation_error_message='A curated reference needs its English name.'),
        ),
    ]
