# Generated by Django 5.2.3 on 2025-11-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_macronutrient_labels_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macronutrient',
            options={'ordering': ['order_index']},
        ),
    ]
