# Generated by Django 5.2.3 on 2026-10-04 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_curated_reference_needs_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefood',
            name='food_subgroup',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sourcefoodnutrient',
            name='maximum',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="The highest value the source's data gives, when it says.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0, message='Amount cannot be negative')]),
        ),
        migrations.AddField(
            model_name='sourcefoodnutrient',
            name='minimum',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="The lowest value the source's data gives, when it says.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0, message='Amount cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='sourcefoodnutrient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Empty when the source did not measure it. Below the detection limit, this is the limit.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0, message='Amount cannot be negative')]),
        ),
    ]
