# Generated by Django 5.2.3 on 2026-10-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_source_food_range_and_precision'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nutrientcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='nutrient_component_factor_is_positive'),
        ),
    ]
