# Generated by Django 5.2.3 on 2025-11-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_macronutrient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='macronutrient',
            name='name_in_form',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
