# Generated by Django 5.2.3 on 2026-10-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_nutrient_component_factor_is_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttaxon',
            name='ciqual_food_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ingredienttaxon',
            name='ciqual_proxy_food_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
