# Generated by Django 5.2.3 on 2026-10-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_taxon_ciqual_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients_text',
            field=models.TextField(blank=True, default='', help_text='The ingredient list as the label prints it.'),
        ),
    ]
