# Generated by Django 5.2.3 on 2026-10-06 00:01

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_ingredients_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='products.referenceingredient'),
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Notes for whoever curates it, such as what it was created from.')),
                ('status', models.CharField(choices=[('to_review', 'To review'), ('curated', 'Curated')], default='to_review', max_length=10)),
                ('components', models.ManyToManyField(blank=True, help_text='The ingredients it is made of, when the label lists none.', related_name='used_in_preparations', to='products.referenceingredient')),
                ('source_foods', models.ManyToManyField(blank=True, related_name='preparations', to='products.sourcefood')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='products.preparation'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('product', 'parent', 'preparation'), name='unique_preparation_per_product_parent'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('product', 'preparation'), name='unique_root_preparation_per_product'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('preparation__isnull', True), ('reference__isnull', False)), models.Q(('preparation__isnull', False), ('reference__isnull', True)), _connector='OR'), name='ingredient_is_a_reference_or_a_preparation', violation_error_message='An ingredient is a reference or a preparation, not both.'),
        ),
        migrations.AddConstraint(
            model_name='preparation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_en'), condition=models.Q(('name_en', ''), _negated=True), name='unique_preparation_name_en'),
        ),
        migrations.AddConstraint(
            model_name='preparation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_fr'), condition=models.Q(('name_fr', ''), _negated=True), name='unique_preparation_name_fr'),
        ),
        migrations.AddConstraint(
            model_name='preparation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name_en', ''), _negated=True), models.Q(('name_fr', ''), _negated=True), _connector='OR'), name='preparation_has_a_name'),
        ),
        migrations.AddConstraint(
            model_name='preparation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'curated'), _negated=True), models.Q(('name_en', ''), _negated=True), _connector='OR'), name='curated_preparation_has_name_en', violation_error_message='A curated preparation needs its English name.'),
        ),
    ]
