# Generated by Django 5.2.3 on 2026-10-06 19:49

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Notes for whoever curates it, such as what it was created from.')),
                ('status', models.CharField(choices=[('to_review', 'To review'), ('curated', 'Curated')], default='to_review', max_length=10)),
                ('code', models.CharField(blank=True, help_text='Its E number, such as E330. Blank when it has none.', max_length=10)),
                ('function', models.CharField(blank=True, choices=[('acid', 'Acid'), ('acidity_regulator', 'Acidity regulator'), ('anti_caking_agent', 'Anti-caking agent'), ('anti_foaming_agent', 'Anti-foaming agent'), ('antioxidant', 'Antioxidant'), ('bulking_agent', 'Bulking agent'), ('carrier', 'Carrier'), ('colour', 'Colour'), ('emulsifier', 'Emulsifier'), ('emulsifying_salt', 'Emulsifying salt'), ('firming_agent', 'Firming agent'), ('flavour_enhancer', 'Flavour enhancer'), ('flour_treatment_agent', 'Flour treatment agent'), ('foaming_agent', 'Foaming agent'), ('gelling_agent', 'Gelling agent'), ('glazing_agent', 'Glazing agent'), ('humectant', 'Humectant'), ('modified_starch', 'Modified starch'), ('packaging_gas', 'Packaging gas'), ('preservative', 'Preservative'), ('propellant', 'Propellant'), ('raising_agent', 'Raising agent'), ('sequestrant', 'Sequestrant'), ('stabiliser', 'Stabiliser'), ('sweetener', 'Sweetener'), ('thickener', 'Thickener')], help_text='What it is used for, when it is known.', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditiveNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, help_text="Per 100 g of the additive, in the nutrient's unit.", max_digits=14, validators=[django.core.validators.MinValueValidator(0, message='Amount cannot be negative')])),
                ('note', models.TextField(blank=True, help_text='Where the figure comes from: its specification, or its formula.')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_is_a_reference_or_a_preparation',
        ),
        migrations.AddField(
            model_name='additive',
            name='source_foods',
            field=models.ManyToManyField(blank=True, related_name='additives', to='products.sourcefood'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='additive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='products.additive'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('product', 'parent', 'additive'), name='unique_additive_per_product_parent'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('product', 'additive'), name='unique_root_additive_per_product'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('additive__isnull', True), ('preparation__isnull', True), ('reference__isnull', False)), models.Q(('additive__isnull', True), ('preparation__isnull', False), ('reference__isnull', True)), models.Q(('additive__isnull', False), ('preparation__isnull', True), ('reference__isnull', True)), _connector='OR'), name='ingredient_is_a_reference_a_preparation_or_an_additive', violation_error_message='An ingredient is a reference, a preparation or an additive, and only one of them.'),
        ),
        migrations.AddField(
            model_name='additivenutrient',
            name='additive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='products.additive'),
        ),
        migrations.AddField(
            model_name='additivenutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.nutrient'),
        ),
        migrations.AddConstraint(
            model_name='additive',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_en'), condition=models.Q(('name_en', ''), _negated=True), name='unique_additive_name_en'),
        ),
        migrations.AddConstraint(
            model_name='additive',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_fr'), condition=models.Q(('name_fr', ''), _negated=True), name='unique_additive_name_fr'),
        ),
        migrations.AddConstraint(
            model_name='additive',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), condition=models.Q(('code', ''), _negated=True), name='unique_additive_code', violation_error_message='An additive already has this E number.'),
        ),
        migrations.AddConstraint(
            model_name='additive',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name_en', ''), _negated=True), models.Q(('name_fr', ''), _negated=True), _connector='OR'), name='additive_has_a_name'),
        ),
        migrations.AddConstraint(
            model_name='additive',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'curated'), _negated=True), models.Q(('name_en', ''), _negated=True), _connector='OR'), name='curated_additive_has_name_en', violation_error_message='A curated additive needs its English name.'),
        ),
        migrations.AddConstraint(
            model_name='additivenutrient',
            constraint=models.UniqueConstraint(fields=('additive', 'nutrient'), name='unique_nutrient_per_additive'),
        ),
    ]
