# Generated by Django 5.2.3 on 2026-10-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_load_additives'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='preparation_components',
            field=models.ManyToManyField(blank=True, help_text='The preparations it is made of, when the label lists none.', related_name='used_in_preparations', to='products.preparation'),
        ),
    ]
