# Generated by Django 5.2.3 on 2026-01-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_ingredient_unique_ingredient_per_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_level_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='group_level_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
