# Generated by Django 5.2.3 on 2026-02-16 14:22

import django.db.models.deletion
import quantityfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_group_level_1_product_group_level_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientref',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='ingredientref',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='ingredientref',
            name='monounsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='ingredientref',
            name='polyunsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='ingredientref',
            name='proteins',
        ),
        migrations.RemoveField(
            model_name='ingredientref',
            name='saturated_fat',
        ),
        migrations.CreateModel(
            name='IngredientRefMacronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', quantityfield.fields.QuantityField(base_units='g', null=True, unit_choices=['g'])),
                ('ingredient_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredientref')),
                ('macronutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.macronutrient')),
            ],
            options={
                'verbose_name': 'IngredientRef Macronutrient',
                'verbose_name_plural': 'IngredientRef Macronutrients',
                'ordering': ['ingredient_ref', 'macronutrient'],
            },
        ),
        migrations.AddField(
            model_name='ingredientref',
            name='macronutrients',
            field=models.ManyToManyField(through='products.IngredientRefMacronutrient', to='products.macronutrient'),
        ),
    ]
