# Generated by Django 5.2.3 on 2026-02-27 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_ingredient_parent_alter_ingredient_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrefmacronutrient',
            name='amount_g',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in g/100g of the macronutrient in the reference ingredient', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='energy_kj',
            field=models.IntegerField(default=0, help_text='Energy in kJ/100g of the product', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Energy cannot be negative'), django.core.validators.MaxValueValidator(limit_value=100000, message='Energy seems too high')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmacronutrient',
            name='amount_g',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in g/100g (canonical unit g) of the macronutrient in the product', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvitamin',
            name='amount_ug',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Amount in µg/100g (canonical unit µg) of the vitamin in the product', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Amount cannot be negative'), django.core.validators.MaxValueValidator(1000000, message='Amount too large')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvitamin',
            name='usual_unit',
            field=models.CharField(choices=[('mg', 'mg'), ('µg', 'µg')], default='mg', help_text='Unit used for this vitamin', max_length=5),
        ),
    ]
