# Generated by Django 5.2.3 on 2026-02-27 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_ingredientrefmacronutrient_amount_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrefmacronutrient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='productmacronutrient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='productvitamin',
            name='amount',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Percentage of the ingredient in the product', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Percentage cannot be negative'), django.core.validators.MaxValueValidator(limit_value=100, message='Percentage too large')]),
        ),
    ]
