# Generated by Django 5.2.3 on 2026-09-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_ingredientrefmacronutrient_amount_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productmacronutrient',
            constraint=models.UniqueConstraint(fields=('product', 'macronutrient'), name='unique_product_macronutrient'),
        ),
        migrations.AddConstraint(
            model_name='productvitamin',
            constraint=models.UniqueConstraint(fields=('product', 'vitamin'), name='unique_product_vitamin'),
        ),
    ]
