"""
This type stub file was generated by pyright.
"""

from pint import UnitRegistry
from typing import List

def check_matching_unit_dimension(ureg: UnitRegistry, base_units: str, units_to_check: List[str]) -> None:
    """
    Check if all units_to_check have the same Dimension like the base_units
    If not
    :raise DimensionalityError
    """
    ...

