"""
This type stub file was generated by pyright.
"""

from django.forms.widgets import MultiWidget

class QuantityWidget(MultiWidget):
    def __init__(self, *, attrs=..., base_units=..., allowed_types=...) -> None:
        ...
    
    def get_choices(self, allowed_types=...): # -> list[tuple[Any | str, Any | str]]:
        ...
    
    def decompress(self, value): # -> list[Number | Any | None] | list[Any | PlainUnit] | list[Any | None]:
        """This function is called during rendering

        It is responsible to split values for the two widgets
        """
        ...
    


