# Hand-written, unlike the rest of typings/: django-environ annotates every
# `default` parameter with its own NoValue sentinel type, so any real default
# (env.bool("X", default=False)) is a type error. Covers what config/settings
# uses.
from typing import Any

class Env:
    def __init__(self, **scheme: Any) -> None: ...
    def __call__(
        self,
        var: str,
        cast: Any = ...,
        default: Any = ...,
        parse_default: bool = ...,
    ) -> Any: ...
    def str(self, var: str, default: str | None = ..., multiline: bool = ...) -> str: ...
    def bool(self, var: str, default: bool = ...) -> bool: ...
    def int(self, var: str, default: int = ...) -> int: ...
    def list(self, var: str, cast: Any = ..., default: list[Any] = ...) -> list[str]: ...
    def db(
        self, var: str = ..., default: str = ..., engine: str | None = ...
    ) -> dict[str, Any]: ...
    db_url = db
    @classmethod
    def read_env(
        cls, env_file: Any = ..., overwrite: bool = ..., **overrides: Any
    ) -> None: ...
