#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# A pid file left behind by an unclean shutdown stops beat from starting again.
rm -f './celerybeat.pid'

exec celery -A config.celery_app beat -l INFO
