# Generated by Django 5.2.3 on 2025-10-30 21:31

import django.db.models.deletion
import django.db.models.functions.text
import products.fields
import quantityfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', products.fields.EAN13Field(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('energy', quantityfield.fields.QuantityField(base_units='kJ', null=True, unit_choices=['kJ', 'kcal'])),
            ],
        ),
        migrations.CreateModel(
            name='Macronutrient',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_macronutrient_name_case_insensitive')],
            },
        ),
        migrations.CreateModel(
            name='ProductMacronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', quantityfield.fields.QuantityField(base_units='g', null=True, unit_choices=['g'])),
                ('macronutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.macronutrient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Macronutrient',
                'verbose_name_plural': 'Product Macronutrients',
                'ordering': ['product', 'macronutrient'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='macronutrients',
            field=models.ManyToManyField(related_name='products', through='products.ProductMacronutrient', to='products.macronutrient'),
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('common_name', models.TextField(blank=True, max_length=100)),
                ('atc_code', models.CharField(max_length=7, unique=True)),
                ('chembl_id', models.CharField(max_length=12, unique=True)),
                ('default_unit_in_form', models.CharField(choices=[('mg', 'mg'), ('µg', 'µg')], default='mg', max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_vitamin_name_case_insensitive'), models.UniqueConstraint(django.db.models.functions.text.Upper('atc_code'), name='unique_vitamin_atc_code_case_insensitive'), models.UniqueConstraint(django.db.models.functions.text.Upper('chembl_id'), name='unique_vitamin_chembl_id_case_insensitive')],
            },
        ),
        migrations.CreateModel(
            name='ProductVitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', quantityfield.fields.QuantityField(base_units='mg', null=True, unit_choices=['mg', 'µg'])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vitamin')),
            ],
            options={
                'verbose_name': 'Product Vitamin',
                'verbose_name_plural': 'Product Vitamins',
                'ordering': ['product', 'vitamin'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins',
            field=models.ManyToManyField(related_name='products', through='products.ProductVitamin', to='products.vitamin'),
        ),
    ]
