# Generated by Django 5.2.3 on 2025-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_ingredientref_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_reference_exists',
            field=models.GeneratedField(db_persist=True, expression=models.Q(('reference__isnull', False)), output_field=models.BooleanField()),
        ),
    ]
