# Generated by Django 5.2.3 on 2025-12-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_ingredient_is_reference_exists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='is_reference_exists',
            new_name='has_reference',
        ),
    ]
