# Generated by Django 5.2.3 on 2025-12-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_is_reference_exists_ingredient_has_reference'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_ingredient_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_root_ingredient_name'),
        ),
    ]
