# Generated by Django 5.2.3 on 2025-12-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_ingredient_unique_ingredient_per_parent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_root_ingredient_name',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('product', 'parent', 'name'), name='unique_ingredient_per_product_parent'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('product', 'name'), name='unique_root_ingredient_per_product'),
        ),
    ]
