# Generated by Django 5.2.3 on 2026-02-23 20:51

import django.db.models.deletion
import quantityfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_ingredientref_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ingredients', to='products.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='products.ingredientref'),
        ),
        migrations.AlterField(
            model_name='ingredientrefmacronutrient',
            name='amount',
            field=quantityfield.fields.QuantityField(base_units='g', default=0, unit_choices=['g']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='energy',
            field=quantityfield.fields.QuantityField(base_units='kJ', default=0, unit_choices=['kJ', 'kcal']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmacronutrient',
            name='amount',
            field=quantityfield.fields.QuantityField(base_units='g', default=0, unit_choices=['g']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvitamin',
            name='amount',
            field=quantityfield.fields.QuantityField(base_units='mg', default=0, unit_choices=['mg', 'µg']),
            preserve_default=False,
        ),
    ]
