# Generated by Django 5.2.3 on 2026-02-27 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_amount_to_amoung_g_transfer_productmacronutrient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrefmacronutrient',
            name='amount_g',
            field=models.DecimalField(decimal_places=2, help_text='Amount in g/100g of the macronutrient in the reference ingredient', max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Amount cannot be negative'), django.core.validators.MaxValueValidator(limit_value=100, message='Amount too large')]),
        ),
        migrations.AlterField(
            model_name='productmacronutrient',
            name='amount_g',
            field=models.DecimalField(decimal_places=2, help_text='Amount in g/100g (canonical unit g) of the macronutrient in the product', max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Amount cannot be negative'), django.core.validators.MaxValueValidator(limit_value=100, message='Amount too large')]),
        ),
        migrations.AlterField(
            model_name='productvitamin',
            name='amount_ug',
            field=models.DecimalField(decimal_places=3, help_text='Amount in µg/100g (canonical unit µg) of the vitamin in the product', max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Amount cannot be negative'), django.core.validators.MaxValueValidator(limit_value=1000000, message='Amount too large')]),
        ),
    ]
